Ext.define('ianMizi.model.AyohaRewardEvent.AyohaRewardEvent_RespondModel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
      'ID',
      'AccountName',
      'AccountPhoneNo',
      'PlayerID',
      'AccountPhoto',
      'RespondStatus_IwillAttendCount',
      'RespondStatus_InterestedCount',
      'EventCode',
      'SubscriberAccNo',
      'EnterpriseAccNo',
      'RespondStatus',
      'CreatedDate',
      'CreatedDate_dateOnly',
      'CreatedBy',
      'ModifiedDate',
      'ModifiedDate_dateOnly',
      'ModifiedBy',
      'RowStatus',
      'Noted',
      'RowNumber',
      'EventType',
      'EventName',
      'EventStartDate',
      'EventStartTime',
      'EventEndDate',
      'EventEndTime',
      'EventDescription',
      'EventCategoryCode',
      'EventLocationCoordinate',
      'EventLocationName',
      'EventCoverPhoto',
      'EventUrlTicket',
      'EventStatus',
      'EventCoverPhotoName', 
      'EventStartDate_Day',      
      'EventStartDate_Month', 
      'EventEndDate_Day',      
      'EventEndDate_Month', 
        ]
    }
});
