Ext.define('ianMizi.model.DashboardMerchant.DashboardMerchantModel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            'ThisWeekCountsStamp',
                 'ThisWeekCountsPoint',
                 'TotalCountStamp',
                 'TotalCountPoint',
                 'TotalMembershipCard',
                 'AyohaPoint',
                 'TotalMembers',
                 'LatestPointCampaignCode',
                 'LatestStampCampaignCode',
                 'LatestPointCampaignCode_SubscriberAccNo',
                 'LatestStampCampaignCode_SubscriberAccNo',
                 'LatestcountsPoint',
                 'LatestPointedByDate',
                 'LatestStamp',
                 'LatestStampedByDate',
                 'LatestStampedMemberName',
                 'LatestPointMemberName',
                 'PNUnread',
                 'NewRedemption',
                 'CountLoyaltyStamp',
                 'CountLoyaltyPoint',
                 'CountMembershipDiscountUsed',
                 'CountContestant',
                 'CountVoucherUsed',
                 'CountEventRespond',
                 'CountVoucherUsedDate',
                 'CountContestantDate',
                 'CountMembershipDiscountUsedDate',
                 'CountLoyaltyPointDate',
                 'CountLoyaltyStampDate',
                 'CountEventRespondDate',
                 'NewPaidOrder',
                 'MembershipCardCount',
                 'NewRequestForApproval',
                 'CountMembershipCard',
                 'CountMembershipCardPrivilege',
                 'CountPrivilgeOnMembershipCard',
                 'CountQrCodeMembershipCampaign',
                 'CountAyohaSaleItem',
                 'QRDescCheckBox',
                 'QRDescBtn',
        ]
    }
});